
## Genaral config about pg_sqlbrancher
pg_sqlbrancher_config:
  daemon:
    lockfile_path: "/path/to/parse_daemon.lock"
    socket_lockfile_path: "/path/to/socket.lock"
  log:
    log_path: "/test/log"
    log_level: "INFO"  # DEBUG / INFO / WARNING / ERROR / CRITICAL 
    log_refile_period: "month"  # year / month / day
  connection_pool:
    min_connections: 10
    max_connections: 100
  socket:
    recive:
      host: 192.168.150.30
      port: 6543
    send:
      host: 192.168.150.30
      port: 6543

## PostgreSQL connection info
postgres_connectionInfo:
  user_info:
    database: "experdb"
    username: "experdba"
    userpassword: "experdba"
  server:
    - server_name : "node1"
      host: 192.168.150.10
      port: 5432
    - server_name : "node2"
      host: 192.168.150.20
      port: 5432